### ISSUE TITLE
Not working with Gmail

### ISSUE THREAD

**Issue by orschiro** [sv3k/topscroll#2]
Hi there, 

Is it possible that topscroll is not working with Gmail?

If I click on the edge at the left side of the screen, it does not scroll to the top. 

Thanks, 

Robert

**Comment by sv3k** [comment]
You know what? I think I have an idea how to make it work on such websites 😃 
I'll post an update soon.

**Comment by orschiro** [comment]
Nice, thanks for the update! :-)
