### ISSUE TITLE
Issue with couple monitors

### ISSUE THREAD

**Issue by volosovich** [sv3k/topscroll#8]
If you have couple monitor (2 or 3), it's big problem to catch left side browser for click. Maybe need to add line with width 3-5 px for click.

**Comment by sv3k** [comment]
An option to have 10px div have been added in [1.8.0 release](https://github.com/sv3k/topscroll/releases/tag/v1.8.0). Enjoy!

**Comment by volosovich** [comment]
thank you very much. I test new version and write result.
